title: "k8sh3qbxrn"
author: "Ari H <3"
description: "welcome to my labyrinth"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "aboutme.html", title: "About Me + Links"}
  - {file: "scenepacks.html", title: "My Scenepacks"}
  - {title: "My Coloring Packs (free!)"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Soundcloud, icon: soundcloud, url: "https://soundcloud.com/k8sh3qbxrn"}
  - {title: Subscribe, icon: youtube, url: "https://www.youtube.com/channel/UCdSjzffclsoeTtIDsIxINmA"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
